### ISSUE TITLE
glpk.h: No such file or directory when building from source

### ISSUE THREAD

**Issue by felipenoris** [coin-or/coinbrew#14]
Hi!

I'm running the following script to build symphony:

```
git clone https://www.github.com/coin-or/coinbrew \
    && cd coinbrew \
    && ./coinbrew fetch --no-prompt SYMPHONY:stable/5.6 \
    && ./coinbrew build --no-prompt SYMPHONY --prefix=/usr/local --parallel-jobs="$(nproc --all)" 
```

The build process fails with the following message:

```
/root/coinbrew/CoinUtils/CoinUtils/src/CoinMpsIO.cpp:2766:18: fatal error: glpk.h: No such file or directory
 #include "glpk.h"
                  ^
```

**Comment by tkralphs** [comment]
@svigerske It seems that installing with a prefix is broken again by the changes I made related to #11. We now pre-install using `DESTDIR` (see #6 and 85cfa34cdca9), but we also now disabled the use of the `-uninstalled.pc` files (in cc52c43c272b), so we have two issues. First, the `.pc` are not found because they are in `DESTDIR` rather than in the final prefix location. This can be fixed by specifying the install location as `DESTDIR` with `--with-coin-instdir`, but then we have the issue that the paths in the `.pc` files are the final install paths rather than the `DESTDIR` paths, so the build fails. 

The obvious quick fix is to re-enable the use of the `-uninstalled.pc` files by removing 
```
export PKG_CONFIG_DISABLE_UNINSTALLED=TRUE
```
which does fix the problem, but then raises the issues we discussed in #11. I guess this will all be fixed once we complete the overhaul of [BuildTools](https://github.com/coin-or-tools/BuildTools), so maybe the best short-term solution is this quick fix, which should work well for now. Thoughts? Looping in @LouHafer, too, so he is aware.

**Comment by svigerske** [comment]
OK, sounds good.

**Comment by tkralphs** [comment]
@svigerske Is there any point in doing the pre-install, given that we will be essentially just building against uninstalled versions? I actually don't see a long-term way to easily do the pre-install using the `.pc` files. The paths will always be wrong unless we provide `-uninstalled.pc` files that are pre-installed with the `DESTDIR` paths. Maybe we should give up on the pre-install step?

**Comment by svigerske** [comment]
Of course we should. I thought you had a reason to implement that. :)

**Comment by tkralphs** [comment]
It's what we discussed doing long back because we didn't want to do the final install of dependent projects until we knew that the whole thing would work correctly once installed. It wouldn't be ideal to have installed several dependencies before realizing that the target package actually doesn't build correctly. It's easy to remove the pre-installed stuff and start over, but more difficult to remove installed packages. I guess corruptions could occur if one is not careful.

**Comment by svigerske** [comment]
Hmm, we discussed that? Na, maybe.

Anyway, coinbrew is supposed to be like a package manager, I remember. It's not uncommon there that they install one package after another and if something fails I don't think that previous installations are undone. Also my system's yaourt, which may also compile and build, wouldn't undo installation of dependencies. So I think it would be ok to do a complete configure/make/make test/make install for one project after another. Maybe have an option to skip the make test or ignore its outcome :).

**Comment by tkralphs** [comment]
We also wanted to avoid linking against uninstalled packages during testing in case there was something that should have been installed, but wasn't. It could be possible unit tests when building against uninstalled versions, but not against installed.

 The other way to go would be to just not worry and do the final install of each project as they are built, then link against these installed versions in each step. But this would mean that you have to install in order to build, which is not ideal. I guess I will just go back to the way it was for now, but we should sort this out.

**Comment by svigerske** [comment]
I think we should install one package before configuring and building the next one.

Ah yes, now I remember that one argument against that was that install might need root privileges. yaourt calls the install-step via sudo, and insists on not being root for the build-step. So you could just do the make install via sudo if the install directory isn't writable?

**Comment by tkralphs** [comment]
Oops, my previous comment was made before I read your previous comment. Anyway, OK, I guess if one want to build and not install outside the build directory, just not specifying a prefix currently accomplishes that. 

At the moment, unit tests are not run by default, only if the option is specified.

**Comment by tkralphs** [comment]
@felipenoris The issue should be fixed for you now, but based on this discussion, I guess there may be some further changes. These shouldn't affect you much if you don't need to run the install step as root.

**Comment by tkralphs** [comment]
@svigerske Seems we can either (1) run the `install` command as `sudo` within the script (which may require the user to enter a password each time, depending the timeout for credential caching) or (2) require the script to be run as `sudo`, but run most of the commands in user mode. Any ideas/suggestions? I guess I'll create a branch to work on this.

**Comment by svigerske** [comment]
I think the more usual way would be to do (1). Only do sudo when necessary.

**Comment by felipenoris** [comment]
@tkralphs , thanks for your work on this! It works now.

**Comment by tkralphs** [comment]
By the way, installation is now done in a more principled way. See #16.
