### ISSUE TITLE
fatal: unable to access 'https://github.com/coin-or/FlopC++/': The requested URL returned error: 400

### ISSUE THREAD

**Issue by pgirardgerad** [coin-or/coinbrew#18]
It appears that this URL doesn't exist anymore.
Changing the coinbrew slightly and first downloading FlopCpp seems to workaround the problem.

It might be caused by the Dependency file in COIN-OR-OptimizationSuite directory.

```
index 8fbdf9e..20a3a77 100755
--- a/coinbrew
+++ b/coinbrew
@@ -399,7 +399,7 @@ function user_prompts {
         echo " 2. Clp"
         echo " 3. Cbc"
         echo " 4. DyLP"
-        echo " 5. FlopC++"
+        echo " 5. FlopCpp"
         echo " 6. Vol"
         echo " 7. SYMPHONY"
         echo " 8. Smi"
@@ -425,7 +425,7 @@ function user_prompts {
             2)  main_proj=Clp;;
             3)  main_proj=Cbc;;
             4)  main_proj=DyLP;;
-            5)  main_proj=FlopC++;;
+            5)  main_proj=FlopCpp;;
             6)  main_proj=Vol;;
             7)  main_proj=SYMPHONY;;
             8)  main_proj=Smi;;

```

**Comment by tkralphs** [comment]
This was because the URLs if the SVN and git projects did not match (I switched from FlopC++ to FlopCpp when moving from SVN for technical reasons). I did patch coinbrew to account for this, but it's actually mott, as FlopC++ is now maintained on Github (although it said it was still mirrored, this was also fixed). I now updated the Dependencies in the Optimization Suite to point directly to Github for those projects that are maintained in git now. Everything should work. Thanks for the report!
