### ISSUE TITLE
How to get ipopt to build without HSL/ASL but with Lapack/Blas?

### ISSUE THREAD

**Issue by lamont-granquist** [coin-or/coinbrew#23]
I found the `--skip` option and this mostly works:

```
./coinbrew --skip='ThirdParty/HSL ThirdParty/ASL' --no-prompt fetch Ipopt:releases/3.13.0
./coinbrew --skip='ThirdParty/HSL ThirdParty/ASL' --no-prompt build Ipopt:releases/3.13.0
```

But what incantations are necessary to get Ipopt to build also against Blas + Lapack?  I tried putting a Dependencies file in the same dir as coinbrew, but that gets ignored when main_proj is specified and trying to add Ipopt as a "Dependency" in that file and not setting the main_proj winds up with complaints about main_proj being required if --no-prompt is specified.

I'm not sure if this is a feature request to add the inverse of --skip, or to better support a parent Dependencies file, or if its just a doc request because I can't figure it out...

**Comment by tkralphs** [comment]
If you want to build from source, you need to add Blas and Lapack to Ipopt's existing Dependencies file, e.g., here: https://github.com/coin-or/Ipopt/blob/master/.coin-or/Dependencies. But since they are not there already, I suspect there is a reason. According to the `configure.ac`, Blas and Lapack is required, so I suspect that if you are not getting any configuration errors, then Blas and Lapack are being found installed somewhere already. On OS X and Linux, they are usually installed by default. What OS are you on? You can take a look at `build/Ipopt/*/config.log` to see if there is a message indicating Lapack was found and linked. 

@svigerske would probably have a better answer.

**Comment by svigerske** [comment]
First install Blas and Lapack in your system and then either hope that Ipopt will find it or use the configure flags to point it to it: https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE_LINALG

As far as I remember, any flag passed to coinbrew that it doesn't understand will be passed on to configure.

Don't add some old ThirdParty-Blas/Lapack to the Dependencies file. They are not going to be moved to the updated buildsystem that Ipopt is using.
