### ISSUE TITLE
fetch and build automatically when necessary

### ISSUE THREAD

**Issue by svigerske** [coin-or/coinbrew#3]
It would be nice to be able to just say
```
./coin.install.sh install --main-proj=Ipopt
```
and this would fetch (if still necessary), build (if still necessary), and install Ipopt and its dependencies.
For that, install should support all arguments that fetch and build also do.

Similar for building without having to explicitly fetch first.

**Comment by tkralphs** [comment]
So then would you have a flag that disables the automatic fetching? When you build, it does ask if you want to fetch and you can choose to do it or not. How about automatic fetch only in the case that you don't already have the project checked out and otherwise not? 

At the moment, you can do both steps at once by just specifying `fetch build`. Isn't this good enough? I'm thinking there are many cases where you want to build and you definitely don't want to fetch first, such as you are testing with different version than the ones specifies in Dependencies (like a feature branch) or else you have changes that you haven't committed yet so that you don't want to pull. 

I would want to specify when I intend to fetch and otherwise not. Although I can of course modify the script for myself as I please if it would be better for everyone else to have automatic fetch, I think on the whole, for most use cases, it's better not to have automatic fetch as the default (except maybe in the case that the project doesn't exist).

**Comment by svigerske** [comment]
Only fetch if nothing has been fetched so far, i.e., the source directory doesn't exist, sounds good. I agree that build or install shouldn't just fetch automatically if some source is already present.

**Comment by tkralphs** [comment]
OK, fixed in c8b413a39.
