### ISSUE TITLE
Building with --enable-msvc on Cygwin

### ISSUE THREAD

**Issue by guvenma** [coin-or/coinbrew#35]
I am trying to build OSI using coinbrew on Cygwin /  icl+ifort (version 11).  

I enabled 'msvc' and updated $PATH to reflect icl/ifort environments. 

I get the following error
```
/bin/sh ./libtool --tag=F77 --mode=compile ifort  -MT -O3 -fpp -nologo   -c -o dasum.lo /c/opt/xcoinbrew/ThirdParty/Blas/dasum.f
 ifort -MT -O3 -fpp -nologo -c /c/opt/xcoinbrew/ThirdParty/Blas/dasum.f
ifort: command line warning #10156: ignoring option '/c'; no argument required
```

The problem appears to be the first character of source files (```/c/opt/xcoinbrew/ThirdParty/Blas/dasum.f```). 

It starts with ```/``` causing ```ifort``` to think it is a compiler option. 

I wanted to check how you were able to get around this problem when building with Intel compilers on Cygwin.

**Comment by tkralphs** [comment]
I have not tried to build in Cygwin for a long time now and I've more or less abandoned support of it. With Msys2 and WSL available, Cygwin feels like a dinosaur. Unless you have a good reason for using Cygwin, I think you'll be much happier with one of the other two options. 

With that said, this issue doesn't seem to be specific to Cygwin, as Msys2 also uses `/c` for the root of the `C:\` drive. I guess part of the answer to your question is that I've always built in a directory that is within the MSys file hierarchy (like my home directory), so `/c` doesn't appear in any path. But I guess you might have the same issue with any absolute path, since then that path would be interpreted as an option. Although I guess that it might be OK as long as the path doesn't being with a directory consisting of a single letter. So maybe `/home` would be OK. But it seems to me that when I build in my home directory on MSys, I might only get relative paths, not sure. 

In 20 years of building on Cygwin and MSys, I've honestly never run into this. I can play with it a little later when I have more time, but I would just try building in your home directory or at least in a path that doesn't being with `/c` and see what you can figure out.

**Comment by guvenma** [comment]
Thanks, that was helpful.  

Switching to ```msys2``` solves the issue, even though the source paths still begin with ```/home```.  

I never managed to get relative paths though..

On the Cygwin end, having ```/home``` didn't help. It is still treated as a compiler option.

**Comment by tkralphs** [comment]
Hmm, that is interesting. I'm a bit surprised, since I would think libtool would handle this somehow. I assume Cygwin is still a supported platform there. We just re-implemented our whole build system to use a modern version of the autotools and in that transition, we might have dropped some patches that were specific to Cygwin. We used to use `cygpath` pervasively for doing path conversion, but MSys seems to handle it automagically and I assumed that most of the patches we had were for bugs that have since been fixed. Anyway, thanks for the data point!
