### ISSUE TITLE
Crosscompiling not working

### ISSUE THREAD

**Issue by pcbouman-eur** [coin-or/coinbrew#40]
Mostly out of curiosity, I'm trying to use coinbrew to build a Windows binary of Cbc using the guide at https://coin-or.github.io/user_introduction.html#windows-1
I am working with Ubuntu 18.4.04 LTS running on top of WSL of Windows 10.
I compiled Cbc using the following two commands
```
./coinbrew fetch Cbc:stable/2.10 --no-prompt
./coinbrew build Cbc --prefix=/mnt/g/tmp/cbc-win32 --no-prompt --build=x86_64-w64-mingw32
```
and although no errors occur, the final binaries are in ELF format, not .exe, which does not seem correct. It does seem the compiler is picking up the build flag, as it mentions:
```
Caching configuration options...
--build=x86_64-w64-mingw32
--with-coin-instdir=/mnt/g/tmp/cbc-win32
Disabling uninstalled packages
```
Am I doing something wrong, is something missing in the guide, or is this an issue with coinbrew?

**Comment by tkralphs** [comment]
So I take it that you are trying to build MinGW-compatible binaries? I haven't actually tried cross-compiling on WSL to produce MinGW binaries, but I believe the configure argument you need is `--host` not `--build`. The `--host` argument specifies on what platform the binaries you're producing are actually supposed to run. The `--build` argument is the platform you're doing the build on (you shouldn't need to specify this). Sorry, I can see why the instructions are a bit misleading. The section on building with gcc is really about building in MSys2, where you do need to specify `--build` (for arcane reasons that are going to be fixed in the near future. In general, you shouldn't need to specify `--build`. 

These days, MSys2 works very nicely for building native Windows binaries and it has a pretty small footprint, so that is an option, but I am curious if you can make the MinGW cross-compile work. Let me know how you make out. Looks like you need to install a package like like `g++-mingw-w64-x86-64` first (I guess you know this).

**Comment by pcbouman-eur** [comment]
Yes, I think MinGW binaries are the only "easy" option from Ubuntu running on WSL, and I indeed installed packages such as `g++-mingw-w64-x86-64` and `gfortran-mingw-w64-x86-64` to compile the blas/lapack dependencies (I could not find a mingw related package for those in the ubuntu repo).

The `--host=x86_64-w64-mingw32` argument indeed does the trick on WSL. I also had to add `--tests none`, but I now get .exe files. If I leave it out, the compilation process of some of the third party dependencies complains that I may want to use `--build` rather than `--host`. If I use both the coinbrew script runs without errors or warnings.

At first, when I tried to run the binaries, Windows complained that `libgcc_s_seh-1.dll` and `libgfortran-4.dll` were missing. I had to copy them together with `libstdc++-6.dll` (I got a very weird error when that is missing) from `/usr/lib/gcc/x86_64-w64-mingw32` in the WSL environment to the same folder as the binaries, and now I can run `clp` and `cbc` succesfully in the Windows environment.

**Comment by tkralphs** [comment]
Cool, good to know. Yes, there would certainly be a dependence on the MinGW DLLs. There's still an advantage to actually building in MSys2 because there you can install and link to packages like `libreadline`, etc., which provide nice additional functionality in the binaries. But then you need to also package those DLLs to get a portable binary. 

By the way, I did make a few updates to the documentation that hopefully makes things a bit clearer.
