### ISSUE TITLE
Error on line 1150, conditional statement

### ISSUE THREAD

**Issue by adowling2** [coin-or/coinbrew#44]
I just downloaded with ``git clone https://www.github.com/coin-or/coinbrew``.

I then ran ``cd ./coinbrew/`` followed by ``chmod u+x coinbrew ``. When I run ``./coinbrew``, I get the following error:
```
./coinbrew: line 1150: conditional binary operator expected
./coinbrew: line 1150: syntax error near `LD_LIBRARY_PATH'
./coinbrew: line 1150: `        if [[ -v LD_LIBRARY_PATH ]]; then'
```

**Comment by adowling2** [comment]
I am using macOS Mojave (10.14.6) if it helps.

**Comment by tkralphs** [comment]
Yes, that is because OS X comes with a really outdated version of `bash` by default. You need to install a recent bash with homebrew. See the full details [here](https://coin-or.github.io/user_introduction.html#macos-1).

**Comment by adowling2** [comment]
Thank you! For the sake of documentation, ``bash`` run from the terminal still pointed to the macOS version even after installing with homebrew. I had to specify the path of the homebrew version of bash to run ``coinbrew``. It worked great!

**Comment by tkralphs** [comment]
Great! Enough people have reported this that I now just added a check to coinbrew for the bash version. 

To set things up so that homebrew tools are preferred over native ones, you just need to change your `PATH`, as described [here](https://superuser.com/questions/324616/how-should-i-set-the-path-variable-on-my-mac-so-the-hombrew-installed-tools-are). I thought this used to happen automagically, but it seems now anymore. 

Oh, and on macOS, as an alternative, there are [homebrew recipes](https://github.com/coin-or-tools/homebrew-coinor) for some COIN-OR projects themselves.
