### ISSUE TITLE
Statically compiled CBC still requires external libraries

### ISSUE THREAD

**Issue by MirkoCovizzi** [coin-or/coinbrew#48]
HI, I'm having an issue in which when compiling (both on Linux and on Windows) through [this guide](https://coin-or.github.io/user_introduction.html#building-from-source) and adding coinbrew's `--static` flag I obtain executables that are not completely statically compiled. On Windows, for example, if I run `cbc.exe` after compilation I'm greeted with a sequence of `.dll`s not found: `libbz2-1`, `libblas`, `liblapack`, `libgmp-10`.

Edit:

Found [this](https://coin-or.github.io/user_introduction#building-static-executables), will see if it works.

Edit 2:

Adding  `--enable-static --disable-shared` doesn't seem to help.

**Comment by tkralphs** [comment]
Yes, it's a bit tricky to get static executables with version 2.10.*, as they use our old (and somewhat outdated) build system. It should be possible, but it's probably a bit system dependent. You need to manually disable any packages that are linked dynamically.

With our new build system (currently available with Cbc's development version in `master`), the `--static` flag should work fine. One of these days, the development version will become Cbc 3.0. I would suggest you try that one and save yourself some hassle (with the caveat that this is the development version, so mileage may vary a little, but it's pretty stable by now).

**Comment by MirkoCovizzi** [comment]
@tkralphs Is there any way to tell `coinbrew` that I want to compile the master version instead of the latest release?

**Comment by tkralphs** [comment]
Yes, sure, just do
```
coinbrew fetch Cbc@master
```
This is documented in Cbc's [README](https://github.com/coin-or/Cbc/blob/master/README.md) and the documentation of [coinbrew](https://coin-or.github.io/coinbrew/)

**Comment by MirkoCovizzi** [comment]
Hi, I've applied your recent suggestion of fetching from master. It appears I'm getting some errors, both on Linux and Windows. I'm attaching a full log for Windows (it's similar to the one on Linux). 

https://pastebin.com/BdXYdcdC

**Comment by svigerske** [comment]
It looks like configure had no luck to figure out how to link against Lapack (when there is `--static`), but Lapack is a necessary dependency of Mumps. Adding `--with-lapack=-llapack -lblas -lgfortran` may help.

**Comment by tkralphs** [comment]
First, if you run coinbrew with `--skip=ThirdParty/Mumps` (or even `--no-third-party`), then it will not try to build Mumps and you will not have the issue. But you will get a version of Cbc that is a bit slower.  

So to address the reason for the failure, it is partly due to a bug in our build system, which Stefan has put in a PR to fix (see coin-or-tools/BuildTools#140). A workaround in the meantime is to follow Stefan's hint.
- In Linux, you can add `--with-lapack=$(pkg-config --libs --static lapack)` (the bug referenced above is that `pkg-config` is not called with `--static` when `coinbrew is). The actual link line depends on what lapack you have installed and may be different on different Linux systems. 
- In MSys2, the `lapack.pc` is actually incorrect and the above trick won't work. I got it to work by adding `--with-lapack="-llpack -lblas -lgfortran -lquadmath"`, which I figured out more or less by trial and error.

**Comment by MirkoCovizzi** [comment]
@tkralphs The two fixes suggested in the second part of the comment still won't compile successfully with my configuration. At the moment I'm not too concerned about performance, so I'll stick with skipping third party components. In any case, thanks to everybody! Will check from time to time to see how the situation develops.

**Comment by tkralphs** [comment]
OK, I'm going to close the issue for now. If someone finds this issue and there is something to be fixed, please reopen. From our side, I think the only bug is the one Stefan now fixed.
