### ISSUE TITLE
configure failure when building Ipopt on macOS

### ISSUE THREAD

**Issue by rdzman** [coin-or/coinbrew#55]
Not sure if there is a better place to start (feel free to redirect me elsewhere) in attempting to track down a new failure I am seeing with building IPOPT using coinbrew on the macOS runners for GitHub Actions. The following was working until recently, (where the Octave install was used subsequently to build the Octave interface to IPOPT) ...

```
brew install octave
git clone https://www.github.com/coin-or/coinbrew
cd coinbrew
./coinbrew fetch Ipopt --no-prompt
./coinbrew build Ipopt --prefix=$HOME/install --test --no-prompt
./coinbrew install Ipopt
```

Something in the chain must have recently changed because now I am seeing a configure failure in the `coinbrew build Ipopt` phase when it runs `configure` for MUMPS. The error is ...
```
configure: WARNING: compilation failed
configure: error: in `/Users/runner/work/matpower/matpower/coinbrew/build/ThirdParty/Mumps/2.1':
configure: error: cannot compile a simple Fortran program
See `config.log' for more details

Configuration failed, re-running with output enabled
```

The more detailed log that followed is attached here: [config_log.txt](https://github.com/coin-or/coinbrew/files/5922144/config_log.txt)

I tried adding `brew install gfortran` before attempting the coinbrew build, but that didn't seem to make a difference.

Any suggestions are appreciated.

**Comment by tkralphs** [comment]
The problem is that the Mumps configuration script did not find a Fortran compiler. It really should fail immediately if no compiler, but it instead still tries to compile a simple program without a compiler name defined, so the failure message is a little bit cryptic. I'm not familiar with the intimate details of the platforms on Github, but if you are doing `brew install gfortran` and it's still not work, I would guess that `/usr/local/bin` is not in the `PATH` on the machine for some reason. You could try explicitly adding `F77=/usr/local/bin/gfortran` to the `coinbrew` command line. I can take a look if you post a link to the actual job on Github if it's public. Otherwise, this seems to be a problem with Github Actions, not anything related to COIN-OR.

**Comment by svigerske** [comment]
It should be `FC=/usr/local/bin/gfortran` instead of `F77`.

**Comment by rdzman** [comment]
Thanks, I'll give that a try.

Here's a link to the job ...
https://github.com/MATPOWER/matpower/runs/1826582988

**Comment by rdzman** [comment]
I tried ...
```
./coinbrew build Ipopt FC=/usr/local/bin/gfortran --prefix=$HOME/install --test --no-prompt
```
Not sure if that is correct, but it didn't seem to make a difference.

https://github.com/MATPOWER/matpower/runs/1831570727

**Comment by rdzman** [comment]
Looks like its a broken gcc install in the GitHub runners. Simply running ...

```
brew reinstall gcc
```

... seems to fix it. Thanks for your time ... and for your work on the COIN software.

**Comment by rdzman** [comment]
Closing this, since it appears to be an issue with the GitHub runners. See https://github.com/actions/virtual-environments/issues/2616 for updates.
