### ISSUE TITLE
coinbrew uninstall fail

### ISSUE THREAD

**Issue by julian-lemos** [coin-or/coinbrew#75]
"coinbrew --help" list an option name "uninstall" but when used, it does not work with flag "All".

**Comment by tkralphs** [comment]
Hmm, this is surprising. I will try to replicate, but if you could be more specific about what you did, I will fix it. In the meantime, you can uninstall packages individually by doing `make uninstall` in the individual build directories, in case you really need to undo something. I can provide more instructions if you need it.

**Comment by julian-lemos** [comment]
Thanks for the fast reply. I built the coin-or-cbc using the following commands taken from you guide

`#!/opt/homebrew/bin/bash`
`wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew`
`chmod u+x coinbrew`
`./coinbrew fetch Cbc@master`
`./coinbrew build Cbc`

Note that I wrapped the installation on .sh as I typically used a .zsh terminal. When I tried to uninstall using the coinbrew I passed the following command

`./coinbrew uninstall All`

coinbrew then messages

`Package will be built in /Users/jlv/test_coin/build`
`Username for 'https://github.com':`

After passing my credential the process fails with the following message:

`Username for 'https://github.com': XXXXXX`
`Password for 'https://XXXXXX@github.com':`
`remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.`
`remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.`
`fatal: Authentication failed for 'https://github.com/coin-or/All/'`

When uninstalling an specific project as "Osi" the uninstall process works as expected. Although, the prompt message says that "Netlib" is missing and proceeds to fetch this content.

I was running this on the following Macbook pro, Apple M1 Pro, macOS 12.4

PS1: The original issue stays "The "uninstall" option actually install the given argument.", which is incorrect. Should this be edited?
PS2: If I want to remove all coin related installed components, I assume it would be enough just deleting the directory containing the whole solution.

**Comment by tkralphs** [comment]
Ah, OK, you are doing some things that are not quite right, but coinbrew should admittedly give you helpful errors. When you do the uninstall, `All` is not valid. It has to be a package that was already previously installed. So if you built `Cbc` and you want to uninstall, then you should just do `coinbrew uninstall Cbc`. This will uninstall Cbc and all of its dependencies.

In general, you are not meant to install Cbc and then uninstall Osi (a partial uninstall). What is happening there is that it is first parsing the dependencies of Osi to see what to uninstall. The fetching of `Netlib` is because `Netlib` is a dependency of Osi but not Cbc. I guess I could allow this kind of thing, but then there should be a check somewhere that says if the user only asks for an uninstall, then there is no need to download additional dependencies. 

For your other questions:
>PS1: The original issue stays "The "uninstall" option actually install the given argument.", which is incorrect. Should this be edited?

Yes, it looks to me like that is not really true.

PS2: If I want to remove all coin related installed components, I assume it would be enough just deleting the directory containing the whole solution.

It depends on where you installed everything. By default, the build takes place in the `build` directory and everything is installed in a separate `dist` directory. Deleting both of these gets you back to a clean state and this is probably easier than `uninstall`. `uninstall` is more necessry if you use the `--prefix` argument to put thing in `/usr/local` or some system directory. In that case, deleting stuff manually is not really an easy option.

**Comment by julian-lemos** [comment]
Thank you for the clear explanation. I think this issue can be closed now :)
I would suggest that perhaps the option "All" could be eliminated of the uninstall list of possible arguments as it is not valid.

**Comment by tkralphs** [comment]
Ah, OK, I see where the `All` option came from. Yes, that was confusing. In fact, the project corresponding to the `All option is the COIN-OR-Optimization-Suite, which is itself an actual project that encompasses all of the other options. So just as the others, you would need to choose that option when installing in order to later uninstall. In other words, if you chose the option in the interactive version of the installer for `All`, you would then need to uninstall `COIN-OR-OptimizationSuite`. I see now that this is completely unclear, so I changed the description corresponding to the `All` option in the interactive installer to hopefully make it clearer. 

I hadn't realize this possibility for confusion before, so thanks for pointing it out! 

I would actually like to add some better error-checking for doing things like uninstalling a project that was not directly installed, if you would not mind opening an issue for that, it would be great.
